### ISSUE TITLE
Option to ignore case when sorting keys

### ISSUE THREAD

**Issue by mgzenitech** [prantlf/jsonlint#27]
please add setting/option to ignore case when sorting keys.

I.e:

```
a
AA
b
BB
c
```

and not:
```
AA
BB
a
b
c
```

**Comment by prantlf** [comment]
Yes, this can be useful. Let me add options to ignore the case, use a locale or keep numeric order of numbers inside the key strings.

**Comment by prantlf** [comment]
Released with [14.1.0](https://github.com/prantlf/jsonlint/releases/tag/v14.1.0), committed in 4387c4b7852ff1f75b533cacd0ba89a953432870.
