### ISSUE TITLE
Enforce newline at end of file

### ISSUE THREAD

**Issue by stevelacey** [prantlf/jsonlint#3]
I don't know whether this should be configurable, or how it plays with the JSON specifications you're adhering to, but I would expect a newline to be enforced at the end of the file, or at least an option to enable that via (though I'd say it's a sensible default).

Thanks for maintaining this fork! There are so many jsonlint's that can't glob/walk directories 😿

**Comment by prantlf** [comment]
Yes, I think that ensuring a newline at the end of the file could be a useful feature. I'm sorry for the long delay.

However, different projects have different coding styles. A trailing line break is not needed to make a JSON file valid, as you see in `JSON.stringify` and `JSON.parse`. A trailing line break is enforced rather in projects, which expect editing files manually.

I introduced a new command line parameter `-r|--trailing-newline` to make this an opt-in feature in 11.1.0.
