### ISSUE TITLE
How can I lint all json files in my project ignoring node_modules directory?

### ISSUE THREAD

**Issue by Shayan-To** [prantlf/jsonlint#6]
How can I lint all json files in my project? When I run it like `jsonlint --sort-keys --in-place .`, it tries to run against the json files in `node_modules` directory. How can I ignore the `node_modules` directory?

**Comment by prantlf** [comment]
A good point! Instead of running `jsonlint .`, you have to list every file directory by `jsonlint dir1 dir2 dir3 file1.json`. Being able to exclude some paths would be a nice feature. Maybe using glob patterns to have the ultimate flexibility.

**Comment by prantlf** [comment]
I added support for BASH patterns in 11.2.0. Instead of specifying a directory, specify a (positive) pattern to identify all JSON files in your project and another (negative) pattern to exclude files from, the `node_modules` directory (from `node_modules` in any subdirectory):

    jsonlint --sort-keys --in-place --log-files '**/*.json' '!**/node_modules'
